### ISSUE TITLE
[CUSA12009]: BLAZBLUE CROSS TAG BATTLE

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#109]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:grs2pbc2awM#C#D Lib:libSceUlt(ver:1) Mod:libSceUlt(major:1 minor:1)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

23d69a90645c36ddc6c887842984953a54c53a12

### Upload your log there

[20240420-123724.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15047843/20240420-123724.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved - sceUltUlthreadRuntimeGetWorkAreaSize

**Comment by GamingDucking** [comment]
Retest

**Comment by igor725** [comment]
> Retest

Is there any particular reason why you left this comment in something like dozen reports?

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.

New missing symbol:
```
Critical Error:Missing Symbol| Name:jw9FkZBXo-g#C#D Lib:libSceUlt(ver:1) Mod:libSceUlt(major:1 minor:1)
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.5-nightly_04.05.24  
**psOff version:**
27812a7fafd6a031c0d404b864800d2d41a7e735

Log:
[20240523-213554.000.zip](https://github.com/SysRay/psOff_compatibility/files/15421843/20240523-213554.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.

New missing symbol:
```
Critical Error:Missing Symbol| Name:jw9FkZBXo-g#C#D Lib:libSceUlt(ver:1) Mod:libSceUlt(major:1 minor:1)
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.5-nightly_04.05.24  
**psOff version:**
27812a7fafd6a031c0d404b864800d2d41a7e735

Log:
[20240523-224023.000.zip](https://github.com/SysRay/psOff_compatibility/files/15422414/20240523-224023.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
```
RuntimeLinker| Critical Error:Missing Symbol| Name:jw9FkZBXo-g#C#D Lib:libSceUlt(ver:1) Mod:libSceUlt(major:1 minor:1)
Exiting
```
```
ExceptionHandler| Error:0x7ffd72edaf4a base:0x7ffd720b0000 C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_cc569e59ca39c5fe\nvoglv64.dll
        vkGetInstanceProcAddr
ExceptionHandler| Error:0x7ffd71870505 base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd7187d40f base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd71854237 base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Critical Error:Access violation: Read at addr:0x7ffd72edaf4a info:0x131000128 , module base:0x7ffd720b0000 C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_cc569e59ca39c5fe\nvoglv64.dll
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.6-nightly_08.06.2024  
**psOff version:**
98ef80dfdd8554aab5edccb09b56dd41bb1340f6

Log:
[20240609-162002.000.zip](https://github.com/user-attachments/files/15752917/20240609-162002.000.zip)
