### ISSUE TITLE
[CUSA00437]: Ultratron

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#55]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:uBIN24Tv2MI#G#G Lib:libSceNgs2(ver:1) Mod:libSceNgs2(major:1 minor:1)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-141617.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14996579/20240416-141617.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved symbol - sceNgs2ReportRegisterHandler

**Comment by igor725** [comment]
The libSceNgs2 library is now fully stubbed, retest please. The game should boot now.

**Comment by Emulator-Team-2** [comment]
## Update:

### Please, describe what you get

The game crashes right after launch with this error:
```
Error:todo sceNgs2SystemCreateWithAllocator(0000000000000000, 000000000C7CF9B8, 000000010400DCB8)
Critical Error:unknown code: 4
Exiting
```
### Game version you are using

01.00

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

e7f77e429c3faabb90c3a4021e949fb2ca09c082

### Upload your log there

[20240418-111827.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15022705/20240418-111827.000.p7d.zip)

**Comment by igor725** [comment]
<https://github.com/SysRay/psOff_public/actions/runs/8737235582?pr=111> should fix unknown code issue

**Comment by Emulator-Team-2** [comment]
@igor725 
Still crashes right after launch.
But the unknown code error no longer occurs.
```
Error:todo sceSystemServiceHideSplashScreen
Error:todo sceGameLiveStreamingInitialize
Error:todo sceNpSetNpTitleId
Error:todo sceNpSetContentRestriction
Error:todo sceNpRegisterStateCallback
Error:todo sceNgs2SystemCreateWithAllocator(0000000000000000, 000000000C7CF9B8, 000000010400DCB8)
Mapping is missing for: 32| (4, 4) (8, 8) (16, 16) (20, 20) (24, 24) (28, 28)
Mapping is missing for: 40| (4, 4) (8, 8) (16, 16) (20, 20) (24, 24) (28, 28)
Console:Audio out started (port#1,256[samples],48000[Hz],2[ch])
Console:  Buffer[0] : 460fd50
Console:  Buffer[1] : 4617d50
```
Looks like logs is empty? (0 KB).

**Comment by igor725** [comment]
It's a private part issue now, wait til next release then

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error.
```
Error:todo sceNgs2SystemCreateWithAllocator(0000000000000000, 00000000047FF9B8, 000000010400DCB8)
Console:Audio out started (port#1,256[samples],48000[Hz],2[ch])
Console:  Buffer[0] : fdcfd50
Console:  Buffer[1] : fdd7d50
Error:todo constBuffer
Critical Error:todo ResourceTable
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.5-nightly_04.05.24  
**psOff version:**
4161cbba3b8799559d8c0a5def574f4a6c483caa

Log:
[20240512-105710.000.zip](https://github.com/SysRay/psOff_compatibility/files/15285625/20240512-105710.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
```
Console:Audio out started (port#1,256[samples],48000[Hz],2[ch])
Console:  Buffer[0] : 1524fd50
Console:  Buffer[1] : 15257d50
ExceptionHandler| Error:0x7ffd78ba2c46 base:0x7ffd78ac0000 E:\PS4\psOff\core.dll
        accessRuntimeLinker
ExceptionHandler| Error:0x7ffd78ba3eda base:0x7ffd78ac0000 E:\PS4\psOff\core.dll
        accessRuntimeLinker
ExceptionHandler| Error:0x7ffd78ba4100 base:0x7ffd78ac0000 E:\PS4\psOff\core.dll
        accessRuntimeLinker
ExceptionHandler| Error:0x7ffd78ba4155 base:0x7ffd78ac0000 E:\PS4\psOff\core.dll
        accessRuntimeLinker
ExceptionHandler| Critical Error:Access violation: Write at addr:0x7ffd78ba2c46 info:0x38b7ad2d08 , module base:0x7ffd78ac0000 E:\PS4\psOff\core.dll
Exiting
```
```
ExceptionHandler| Error:0x7ffd7635a959 base:0x7ffd76300000 C:\Windows\SYSTEM32\vulkan-1.dll
        vkResetEvent
ExceptionHandler| Error:0x7ffd764b6988 base:0x7ffd76470000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd764b1446 base:0x7ffd76470000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd7649f8cf base:0x7ffd76470000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Critical Error:Access violation: Read at addr:0x7ffd7635a959 info:0xffffffffffffffff , module base:0x7ffd76300000 C:\Windows\SYSTEM32\vulkan-1.dll
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.6-nightly_08.06.2024  
**psOff version:**
98ef80dfdd8554aab5edccb09b56dd41bb1340f6

Log:
[20240609-124802.000.zip](https://github.com/user-attachments/files/15751562/20240609-124802.000.zip)
